$(document).ready(function(){
	var data = [
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 1,
	    	day : 10,
	    	amount : 34,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 1,
	    	day : 10,
	    	amount : 34,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 1,
	    	day : 10,
	    	amount : 48,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 1,
	    	day : 10,
	    	amount : 58,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 1,
	    	day : 10,
	    	amount : 12,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 1,
	    	day : 10,
	    	amount : 19,
	    },

	    // Feb
	    
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 2,
	    	day : 14,
	    	amount : 24,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 2,
	    	day : 4,
	    	amount : 16,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 2,
	    	day : 19,
	    	amount : 30,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 2,
	    	day : 20,
	    	amount : 98,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 2,
	    	day : 19,
	    	amount : 24,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 2,
	    	day : 10,
	    	amount : 14,
	    },
	    
	    // Mar
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 3,
	    	day : 14,
	    	amount : 21,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 3,
	    	day : 4,
	    	amount : 26,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 3,
	    	day : 19,
	    	amount : 39,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 3,
	    	day : 20,
	    	amount : 49,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 3,
	    	day : 19,
	    	amount : 22,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 3,
	    	day : 10,
	    	amount : 24,
	    },
	    
	    // Apr
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 4,
	    	day : 14,
	    	amount : 10,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 4,
	    	day : 4,
	    	amount : 29,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 4,
	    	day : 19,
	    	amount : 27,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 4,
	    	day : 20,
	    	amount : 29,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 4,
	    	day : 19,
	    	amount : 32,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 4,
	    	day : 10,
	    	amount : 34,
	    },
	    
	    
	    // May
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 5,
	    	day : 14,
	    	amount : 40,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 5,
	    	day : 4,
	    	amount : 19,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 5,
	    	day : 19,
	    	amount : 37,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 5,
	    	day : 20,
	    	amount : 22,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 5,
	    	day : 19,
	    	amount : 36,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 5,
	    	day : 10,
	    	amount : 39,
	    },
	    
	    // Jun
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 6,
	    	day : 14,
	    	amount : 40,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 6,
	    	day : 4,
	    	amount : 15,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 6,
	    	day : 19,
	    	amount : 15,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 6,
	    	day : 20,
	    	amount : 23,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 6,
	    	day : 19,
	    	amount : 29,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 6,
	    	day : 10,
	    	amount : 31,
	    },
	    
	    // Jul
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 7,
	    	day : 14,
	    	amount : 38,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 7,
	    	day : 4,
	    	amount : 26,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 7,
	    	day : 19,
	    	amount : 13,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 7,
	    	day : 20,
	    	amount : 21,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 7,
	    	day : 19,
	    	amount : 45,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 7,
	    	day : 10,
	    	amount : 20,
	    },
	    
	    // Aug
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 8,
	    	day : 14,
	    	amount : 30,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 8,
	    	day : 4,
	    	amount : 21,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 8,
	    	day : 19,
	    	amount : 38,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 8,
	    	day : 20,
	    	amount : 14,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 8,
	    	day : 19,
	    	amount : 25,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 8,
	    	day : 10,
	    	amount : 31,
	    },
	    
	    // Sep
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 9,
	    	day : 14,
	    	amount : 24,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 9,
	    	day : 4,
	    	amount : 18,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 9,
	    	day : 19,
	    	amount : 10,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 9,
	    	day : 20,
	    	amount : 24,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 9,
	    	day : 19,
	    	amount : 45,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 9,
	    	day : 10,
	    	amount : 21,
	    },
	    
	    // Oct
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 10,
	    	day : 14,
	    	amount : 26,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 10,
	    	day : 4,
	    	amount : 46,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 10,
	    	day : 19,
	    	amount : 48,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 10,
	    	day : 20,
	    	amount : 17,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 10,
	    	day : 19,
	    	amount : 20,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 10,
	    	day : 10,
	    	amount : 3,
	    },
	    
	    // Nov
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 11,
	    	day : 14,
	    	amount : 10,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 11,
	    	day : 4,
	    	amount : 39,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 11,
	    	day : 19,
	    	amount : 16,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 11,
	    	day : 20,
	    	amount : 22,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 11,
	    	day : 19,
	    	amount : 26,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 11,
	    	day : 10,
	    	amount : 26,
	    },
	    
	    // Dec
	    {
	    	employee : {id:1, label:'John Brown'},
	    	department : 1,
	    	year : 2013,
	    	month : 12,
	    	day : 14,
	    	amount : 12,
	    },
	    {
	    	employee : {id:2, label:'Bill Green'},
	    	department : 1,
	    	year : 2013,
	    	month : 12,
	    	day : 4,
	    	amount : 15,
	    },
	    {
	    	employee : {id:3, label:'Daniel White'},
	    	department : 2,
	    	year : 2013,
	    	month : 12,
	    	day : 19,
	    	amount : 18,
	    },
	    {
	    	employee : {id:4, label:'Bryan Gold'},
	    	department : 2,
	    	year : 2013,
	    	month : 12,
	    	day : 20,
	    	amount : 13,
	    },
	    {
	    	employee : {id:5, label:'Suzy Fowler'},
	    	department : 3,
	    	year : 2013,
	    	month : 12,
	    	day : 19,
	    	amount : 29,
	    },
	    {
	    	employee : {id:6, label:'Julia Smith'},
	    	department : 3,
	    	year : 2013,
	    	month : 12,
	    	day : 10,
	    	amount : 12,
	    },
	    
	];
	$.each(data, function(idx, value){
		value.total = 1;
	});
	
	var dimensions = {
	    employee : {
	        label :'Employee', 
	    },
	    department : {
	        label :'Department', 
	        values : function(context) {
	            return [
	                {id:1, label:'Administration'}, 
	                {id:2, label:'Logistics'}, 
	                {id:3, label:'Accounting'}
	            ];
	        },
	    },
	    year : {
	        label :'Year', 
	    },
	    month : {
	        label :'Month', 
	        values : function(context) {
	            return [
                    {id:1, label:'Jan'}, 
                    {id:2, label:'Feb'}, 
                    {id:3, label:'Mar'}, 
                    {id:4, label:'Apr'}, 
                    {id:5, label:'May'}, 
                    {id:6, label:'Jun'}, 
                    {id:7, label:'Jul'}, 
                    {id:8, label:'Aug'}, 
                    {id:9, label:'Sep'}, 
                    {id:10, label:'Oct'}, 
                    {id:11, label:'Nov'}, 
                    {id:12, label:'Dec'}, 
	            ];
	        },
	    },
	    total : {
	        label :'Total', 
	        values : function(context) {
	            return [
	                {id:1, label:'Total'}, 
	            ];
	        },
	    },
	};
	
	$("#pivot").cypivot({
		data : data,
		dimensions : dimensions,
		verticalDimensions : ["total", "year", "month"],
		horizontalDimensions : ["department", "employee"],
		valueDataFields : ['amount'],
		configuration : false,
		resizable : true,
		resizableWidth : true,
		resizableHeight : false,
	});
});